[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Mimi = "e4e893b0-ee5e-52ea-8111-44b3bdec128c"
MimiBRICK = "91f4afc7-28cd-4627-b11a-a83dc9ff1a58"
MimiCIAM = "b45ee815-fc06-4684-baf4-cf48c9e39180"
MimiDICE2016 = "ab869bb0-c23d-11e9-310e-47ac58ee0562"
MimiFAIRv1_6_2 = "02cc1f66-ff46-4bd7-a247-ac068822e639"
MimiGIVE = "08b927d4-7a58-4cf8-85d0-bad32a16dfbc"
MimiRFFSPs = "2561df7e-f865-450a-9449-e82e8f8f9a2f"
MimiSNEASY = "3f1801d0-c5f8-11e9-1568-bf13fd643260"
MimiSSPs = "d73ed964-a3ff-4a3d-ad09-d195fe0d0b35"
Mimi_NAS_pH = "113fc11f-d823-43a8-a074-b997e93e8190"
MooreAg = "20e4a6fe-17a5-11ea-2f9e-a16106eb352d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"
